(() => {
  const lab=document.querySelector('[data-dream-lab]');
  if(!lab)return;
  const scrollStage=lab.querySelector('.dream-scroll'),sticky=lab.querySelector('.dream-sticky'),canvas=lab.querySelector('.dream-canvas'),ctx=canvas.getContext('2d'),scenes=[...lab.querySelectorAll('[data-dream-scene]')],meter=lab.querySelector('.dream-meter'),count=lab.querySelector('[data-dream-count]'),orbs=[...lab.querySelectorAll('[data-memory]')],reveal=lab.querySelector('[data-memory-reveal]'),close=lab.querySelector('[data-memory-close]'),kicker=lab.querySelector('[data-memory-kicker]'),title=lab.querySelector('[data-memory-title]'),copy=lab.querySelector('[data-memory-copy]'),lamp=lab.querySelector('[data-hanging-light]'),lampPull=lab.querySelector('[data-light-pull]'),lampCord=lab.querySelector('[data-light-cord]'),lampBeam=lab.querySelector('[data-light-beam]');
  const memories={
    work:{kicker:'MEMORY / WHAT I DO',title:'Across scales.',copy:'I study architecture and HCI at Carnegie Mellon, moving between buildings, interfaces, product systems, and AI. I like finding the human question hiding inside a technical one.'},
    like:{kicker:'MEMORY / WHAT I LIKE',title:'Rhythm and motion.',copy:'Music, piano, and composition keep me listening. Soccer, basketball, badminton, table tennis, and taekwondo keep me moving. Film, photography, travel, cooking, and poker keep me looking.'},
    home:{kicker:'MEMORY / WHERE I’M FROM',title:'Shenzhen to Pittsburgh.',copy:'I was born in Shenzhen, China. I now study and make work in Pittsburgh—carrying the speed, density, and curiosity of one city into the material character of another.'}
  };
  let width=0,height=0,dpr=1,progress=0,activeScene=0,visible=false,pointerX=.72,pointerY=.5,lastTime=0,blinkStartedAt=0,blinkTimer=0,eyeClosure=0,eyeClosureTime=performance.now(),trail=[],shards=[];
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
  const lampMotion={active:false,dragging:false,returning:false,x:0,y:-220,vx:0,vy:0,targetX:0,targetY:170,last:0,pointerId:null};
  const lampMaxAngle=Math.PI*34/180;
  const lampAnchor=()=>({x:width*.5,y:-8});
  const lampRestY=()=>clamp(height*.22,135,205);
  const renderLamp=()=>{if(!lampMotion.active)return;const anchor=lampAnchor(),dx=lampMotion.x-anchor.x,dy=Math.max(4,lampMotion.y-anchor.y),length=Math.hypot(dx,dy),angle=Math.atan2(dx,dy)*180/Math.PI,beamHalf=(lampBeam.offsetWidth||460)/2;lampCord.style.left=`${anchor.x}px`;lampCord.style.height=`${length}px`;lampCord.style.transform=`rotate(${-angle}deg)`;lampPull.style.transform=`translate3d(${lampMotion.x-56}px,${lampMotion.y}px,0) rotate(${-angle*.42}deg)`;lampBeam.style.transform=`translate3d(${lampMotion.x-beamHalf}px,${lampMotion.y+65}px,0) rotate(${-angle*.18}deg)`;lamp.style.setProperty('--cord-angle',`${angle}deg`)};
  const stopLamp=()=>{lampMotion.active=false;lampMotion.dragging=false;lampMotion.returning=false;lamp.classList.remove('is-active','is-dragging','is-returning');lamp.setAttribute('aria-hidden','true');lampPull.tabIndex=-1};
  const lampFrame=time=>{if(!lampMotion.active)return;const dt=Math.min(.032,Math.max(.008,(time-lampMotion.last)/1000||.016));lampMotion.last=time;if(!lampMotion.dragging){const anchor=lampAnchor(),sway=lampMotion.returning?0:Math.sin(time*.00115)*Math.min(22,width*.025);lampMotion.targetX=anchor.x+sway;const stiffness=lampMotion.returning?58:34,damping=lampMotion.returning?7.2:5.8;lampMotion.vx+=(lampMotion.targetX-lampMotion.x)*stiffness*dt;lampMotion.vy+=(lampMotion.targetY-lampMotion.y)*stiffness*dt;lampMotion.vx*=Math.exp(-damping*dt);lampMotion.vy*=Math.exp(-damping*dt);lampMotion.x+=lampMotion.vx*dt;lampMotion.y+=lampMotion.vy*dt}renderLamp();if(lampMotion.returning&&lampMotion.y<-145&&Math.abs(lampMotion.vy)<45){stopLamp();return}requestAnimationFrame(lampFrame)};
  const dropLamp=()=>{if(lampMotion.active)return;const anchor=lampAnchor();lampMotion.active=true;lampMotion.returning=false;lampMotion.dragging=false;lampMotion.x=anchor.x;lampMotion.y=-210;lampMotion.vx=46;lampMotion.vy=0;lampMotion.targetY=lampRestY();lampMotion.last=performance.now();lamp.classList.add('is-active');lamp.classList.remove('is-returning');lamp.setAttribute('aria-hidden','false');lampPull.tabIndex=0;renderLamp();requestAnimationFrame(lampFrame)};
  const restoreColor=()=>{orbs.forEach(orb=>{orb.classList.remove('is-broken');orb.setAttribute('aria-pressed','false')});sticky.style.setProperty('--lights-off','0');sticky.classList.remove('is-lights-out');document.body.classList.remove('home-lights-out');reveal.classList.remove('is-open');reveal.setAttribute('aria-hidden','true');lampMotion.dragging=false;lampMotion.returning=true;lampMotion.targetY=-260;lampMotion.vy=-980;lampMotion.vx+=(lampMotion.x-lampAnchor().x)*-2.6;lamp.classList.remove('is-dragging');lamp.classList.add('is-returning')};
  const resize=()=>{const rect=sticky.getBoundingClientRect();width=Math.max(1,rect.width);height=Math.max(1,rect.height);dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;ctx.setTransform(dpr,0,0,dpr,0,0)};
  const setScene=next=>{if(next===activeScene)return;activeScene=next;scenes.forEach((scene,index)=>scene.classList.toggle('is-active',index===activeScene));count.textContent=String(activeScene+1).padStart(2,'0')};
  const updateScroll=()=>{const rect=scrollStage.getBoundingClientRect(),range=Math.max(1,rect.height-innerHeight);progress=clamp(-rect.top/range,0,1);meter.style.setProperty('--dream-progress',`${progress*100}%`);setScene(Math.min(scenes.length-1,Math.floor(progress*scenes.length)))};
  const eyeGeometry=()=>{const mobile=width<900,cx=width*(mobile?.57:.74),cy=height*(mobile?.31:.5),rx=Math.min(width*(mobile?.31:.2),250),ry=rx*.57;return{cx,cy,rx,ry}};
  const eyeContains=(clientX,clientY)=>{const rect=sticky.getBoundingClientRect(),{cx,cy,rx,ry}=eyeGeometry(),x=clientX-rect.left,y=clientY-rect.top;return Math.pow((x-cx)/rx,2)+Math.pow((y-cy)/ry,2)<=1};
  const pathEllipse=(cx,cy,rx,ry)=>{ctx.beginPath();ctx.ellipse(cx,cy,rx,ry,0,0,Math.PI*2)};
  const drawEye=(time)=>{const{cx,cy,rx,ry}=eyeGeometry(),elapsed=blinkStartedAt?time-blinkStartedAt:Infinity,blink=elapsed<560?Math.sin(elapsed/560*Math.PI):0,closureDelta=Math.min(40,time-eyeClosureTime||16),closureTarget=sticky.classList.contains('is-lights-out')?1:0;eyeClosureTime=time;eyeClosure+=(closureTarget-eyeClosure)*(1-Math.exp(-closureDelta/170));if(blinkStartedAt&&elapsed>=560)blinkStartedAt=0;const closed=Math.max(blink,eyeClosure),eyeScale=Math.max(.035,1-closed*.965);ctx.save();ctx.translate(cx,cy);ctx.scale(1,eyeScale);ctx.translate(-cx,-cy);ctx.lineWidth=1.4;ctx.strokeStyle='rgba(29,29,31,.18)';pathEllipse(cx,cy,rx,ry);ctx.stroke();pathEllipse(cx,cy,rx*.82,ry*.82);ctx.strokeStyle='rgba(127,138,146,.34)';ctx.stroke();const lookX=(pointerX-.5)*rx*.25,lookY=(pointerY-.5)*ry*.3,iris=ry*.53;ctx.beginPath();ctx.arc(cx+lookX,cy+lookY,iris,0,Math.PI*2);ctx.fillStyle='#c77d5d';ctx.shadowColor='rgba(199,125,93,.22)';ctx.shadowBlur=24;ctx.fill();ctx.beginPath();ctx.arc(cx+lookX,cy+lookY,iris*.38,0,Math.PI*2);ctx.fillStyle='#1d1d1f';ctx.shadowBlur=0;ctx.fill();ctx.beginPath();ctx.arc(cx+lookX-iris*.12,cy+lookY-iris*.16,iris*.08,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();const lidWave=Math.sin(progress*Math.PI*4)*ry*.08;ctx.beginPath();ctx.moveTo(cx-rx,cy);ctx.quadraticCurveTo(cx,cy-ry-lidWave,cx+rx,cy);ctx.strokeStyle='rgba(29,29,31,.7)';ctx.lineWidth=3;ctx.stroke();ctx.beginPath();ctx.moveTo(cx-rx,cy);ctx.quadraticCurveTo(cx,cy+ry+lidWave,cx+rx,cy);ctx.stroke();ctx.restore();if(eyeClosure<.985)drawCrawler(cx,cy,rx,ry,time)};
  const drawCrawler=(cx,cy,rx,ry,time)=>{const angle=-Math.PI*.9+progress*Math.PI*5.4+(reduced?0:time*.00018),x=cx+Math.cos(angle)*rx*1.05,y=cy+Math.sin(angle)*ry*1.22;trail.push({x,y});if(trail.length>42)trail.shift();ctx.beginPath();trail.forEach((point,index)=>{if(index===0)ctx.moveTo(point.x,point.y);else ctx.lineTo(point.x,point.y)});ctx.strokeStyle='rgba(127,138,146,.18)';ctx.lineWidth=2;ctx.stroke();ctx.save();ctx.translate(x,y);ctx.rotate(angle+Math.PI/2);ctx.strokeStyle='#7f8a92';ctx.lineWidth=1.7;for(let side=-1;side<=1;side+=2){for(let leg=0;leg<3;leg++){const ly=(leg-1)*8;ctx.beginPath();ctx.moveTo(side*7,ly);ctx.quadraticCurveTo(side*(17+Math.sin(time*.004+leg)*3),ly-10+leg*6,side*23,ly+2+leg*3);ctx.stroke()}}ctx.beginPath();ctx.arc(0,0,16,0,Math.PI*2);ctx.fillStyle='rgba(255,255,255,.94)';ctx.fill();ctx.strokeStyle='#1d1d1f';ctx.stroke();ctx.beginPath();ctx.arc(0,0,21,0,Math.PI*2);ctx.setLineDash([2,5]);ctx.strokeStyle='rgba(29,29,31,.22)';ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#1d1d1f';ctx.font='700 15px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('A',0,1);ctx.restore()};
  const drawShards=delta=>{shards=shards.filter(shard=>shard.life>0);shards.forEach(shard=>{shard.vy+=.0009*delta;shard.x+=shard.vx*delta;shard.y+=shard.vy*delta;shard.rotation+=shard.spin*delta;shard.life-=delta;ctx.save();ctx.translate(shard.x,shard.y);ctx.rotate(shard.rotation);ctx.beginPath();ctx.moveTo(-shard.size,shard.size);ctx.lineTo(0,-shard.size);ctx.lineTo(shard.size*.7,shard.size);ctx.closePath();ctx.fillStyle=`rgba(${shard.tint},${Math.max(0,shard.life/900)})`;ctx.fill();ctx.restore()})};
  const frame=time=>{if(!visible)return;const delta=Math.min(32,time-lastTime||16);lastTime=time;ctx.clearRect(0,0,width,height);drawEye(time);drawShards(delta);requestAnimationFrame(frame)};
  const burst=orb=>{const rect=orb.getBoundingClientRect(),host=sticky.getBoundingClientRect(),x=rect.left+rect.width/2-host.left,y=rect.top+rect.height*.35-host.top;for(let i=0;i<22;i++){const angle=Math.PI*2*i/22+Math.random()*.24,speed=.08+Math.random()*.16;shards.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed-.08,rotation:Math.random()*6.2,spin:(Math.random()-.5)*.012,size:4+Math.random()*8,life:700+Math.random()*700,tint:i%3===0?'198,255,69':'210,225,235'})}};
  const updateLightLevel=()=>{const switchedOff=orbs.filter(orb=>orb.classList.contains('is-broken')).length;const allOff=switchedOff===orbs.length;sticky.style.setProperty('--lights-off',String(switchedOff/orbs.length));sticky.classList.toggle('is-lights-out',allOff);if(allOff){document.body.classList.add('home-lights-out');dropLamp()}};
  orbs.forEach(orb=>orb.addEventListener('click',()=>{if(orb.classList.contains('is-broken'))return;orb.classList.add('is-broken');orb.setAttribute('aria-pressed','true');updateLightLevel();burst(orb);const memory=memories[orb.dataset.memory];kicker.textContent=memory.kicker;title.textContent=memory.title;copy.textContent=memory.copy;reveal.classList.add('is-open');reveal.setAttribute('aria-hidden','false');if(sticky.classList.contains('is-lights-out')){window.setTimeout(()=>lampPull.focus({preventScroll:true}),420);return}close.focus({preventScroll:true})}));
  close.addEventListener('click',()=>{reveal.classList.remove('is-open');reveal.setAttribute('aria-hidden','true')});
  lampPull.addEventListener('pointerdown',event=>{if(!lampMotion.active||lampMotion.returning)return;event.preventDefault();lampMotion.dragging=true;lampMotion.pointerId=event.pointerId;lampMotion.vx=0;lampMotion.vy=0;lampPull.setPointerCapture(event.pointerId);lamp.classList.add('is-dragging')});
  lampPull.addEventListener('pointermove',event=>{if(!lampMotion.dragging||event.pointerId!==lampMotion.pointerId)return;const rect=sticky.getBoundingClientRect(),anchor=lampAnchor();lampMotion.y=clamp(event.clientY-rect.top-42,70,Math.min(height*.72,610));const cordDrop=Math.max(48,lampMotion.y-anchor.y),maxSide=cordDrop*Math.tan(lampMaxAngle),wantedX=event.clientX-rect.left;lampMotion.x=clamp(wantedX,anchor.x-maxSide,anchor.x+maxSide);renderLamp()});
  const releaseLamp=event=>{if(!lampMotion.dragging||event.pointerId!==lampMotion.pointerId)return;lampMotion.dragging=false;lamp.classList.remove('is-dragging');if(lampPull.hasPointerCapture(event.pointerId))lampPull.releasePointerCapture(event.pointerId);lampMotion.pointerId=null;if(lampMotion.y>lampRestY()+90){restoreColor()}else{lampMotion.targetY=lampRestY();lampMotion.vy=-180}};
  lampPull.addEventListener('pointerup',releaseLamp);lampPull.addEventListener('pointercancel',releaseLamp);
  lampPull.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&lampMotion.active&&!lampMotion.returning){event.preventDefault();restoreColor()}});
  sticky.addEventListener('pointermove',event=>{const rect=sticky.getBoundingClientRect();pointerX=clamp((event.clientX-rect.left)/rect.width,0,1);pointerY=clamp((event.clientY-rect.top)/rect.height,0,1);sticky.classList.toggle('is-eye-hovered',eyeContains(event.clientX,event.clientY))});
  sticky.addEventListener('pointerleave',()=>sticky.classList.remove('is-eye-hovered'));
  sticky.addEventListener('click',event=>{if(event.target.closest('button,a,.memory-reveal')||!eyeContains(event.clientX,event.clientY))return;blinkStartedAt=performance.now();sticky.classList.add('is-eye-blinking');clearTimeout(blinkTimer);blinkTimer=window.setTimeout(()=>sticky.classList.remove('is-eye-blinking'),600)});
  addEventListener('scroll',updateScroll,{passive:true});addEventListener('resize',()=>{resize();updateScroll();if(lampMotion.active&&!lampMotion.dragging){lampMotion.targetY=lampMotion.returning?-260:lampRestY();renderLamp()}});
  new IntersectionObserver(entries=>{const next=entries[0].isIntersecting;if(next&&!visible){visible=true;lastTime=performance.now();requestAnimationFrame(frame)}else visible=next},{rootMargin:'20% 0px'}).observe(sticky);
  orbs.forEach(orb=>orb.setAttribute('aria-pressed','false'));updateLightLevel();resize();updateScroll();
})();
