(() => {
  const lab=document.querySelector('[data-dream-lab]');
  if(!lab)return;
  const scrollStage=lab.querySelector('.dream-scroll'),sticky=lab.querySelector('.dream-sticky'),canvas=lab.querySelector('.dream-canvas'),ctx=canvas.getContext('2d'),scenes=[...lab.querySelectorAll('[data-dream-scene]')],meter=lab.querySelector('.dream-meter'),count=lab.querySelector('[data-dream-count]'),orbs=[...lab.querySelectorAll('[data-memory]')],reveal=lab.querySelector('[data-memory-reveal]'),close=lab.querySelector('[data-memory-close]'),kicker=lab.querySelector('[data-memory-kicker]'),title=lab.querySelector('[data-memory-title]'),copy=lab.querySelector('[data-memory-copy]');
  const memories={
    work:{kicker:'MEMORY / WHAT I DO',title:'Across scales.',copy:'I study architecture and HCI at Carnegie Mellon, moving between buildings, interfaces, product systems, and AI. I like finding the human question hiding inside a technical one.'},
    like:{kicker:'MEMORY / WHAT I LIKE',title:'Rhythm and motion.',copy:'Music, piano, and composition keep me listening. Soccer, basketball, badminton, table tennis, and taekwondo keep me moving. Film, photography, travel, cooking, and poker keep me looking.'},
    home:{kicker:'MEMORY / WHERE I’M FROM',title:'Shenzhen to Pittsburgh.',copy:'I was born in Shenzhen, China. I now study and make work in Pittsburgh—carrying the speed, density, and curiosity of one city into the material character of another.'}
  };
  let width=0,height=0,dpr=1,progress=0,activeScene=0,visible=false,pointerX=.72,pointerY=.5,lastTime=0,blinkStartedAt=0,blinkTimer=0,trail=[],shards=[];
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
  const resize=()=>{const rect=sticky.getBoundingClientRect();width=Math.max(1,rect.width);height=Math.max(1,rect.height);dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;ctx.setTransform(dpr,0,0,dpr,0,0)};
  const setScene=next=>{if(next===activeScene)return;activeScene=next;scenes.forEach((scene,index)=>scene.classList.toggle('is-active',index===activeScene));count.textContent=String(activeScene+1).padStart(2,'0')};
  const updateScroll=()=>{const rect=scrollStage.getBoundingClientRect(),range=Math.max(1,rect.height-innerHeight);progress=clamp(-rect.top/range,0,1);meter.style.setProperty('--dream-progress',`${progress*100}%`);setScene(Math.min(scenes.length-1,Math.floor(progress*scenes.length)))};
  const eyeGeometry=()=>{const mobile=width<900,cx=width*(mobile?.57:.74),cy=height*(mobile?.31:.5),rx=Math.min(width*(mobile?.31:.2),250),ry=rx*.57;return{cx,cy,rx,ry}};
  const eyeContains=(clientX,clientY)=>{const rect=sticky.getBoundingClientRect(),{cx,cy,rx,ry}=eyeGeometry(),x=clientX-rect.left,y=clientY-rect.top;return Math.pow((x-cx)/rx,2)+Math.pow((y-cy)/ry,2)<=1};
  const pathEllipse=(cx,cy,rx,ry)=>{ctx.beginPath();ctx.ellipse(cx,cy,rx,ry,0,0,Math.PI*2)};
  const drawEye=(time)=>{const{cx,cy,rx,ry}=eyeGeometry(),elapsed=blinkStartedAt?time-blinkStartedAt:Infinity,blink=elapsed<560?Math.sin(elapsed/560*Math.PI):0;if(blinkStartedAt&&elapsed>=560)blinkStartedAt=0;ctx.save();ctx.translate(cx,cy);ctx.scale(1,Math.max(.035,1-blink*.965));ctx.translate(-cx,-cy);ctx.lineWidth=1.4;ctx.strokeStyle='rgba(238,238,244,.42)';pathEllipse(cx,cy,rx,ry);ctx.stroke();pathEllipse(cx,cy,rx*.82,ry*.82);ctx.strokeStyle='rgba(8,121,249,.38)';ctx.stroke();const lookX=(pointerX-.5)*rx*.25,lookY=(pointerY-.5)*ry*.3,iris=ry*.53;ctx.beginPath();ctx.arc(cx+lookX,cy+lookY,iris,0,Math.PI*2);ctx.fillStyle='#0879f9';ctx.shadowColor='#0879f9';ctx.shadowBlur=35;ctx.fill();ctx.beginPath();ctx.arc(cx+lookX,cy+lookY,iris*.38,0,Math.PI*2);ctx.fillStyle='#080809';ctx.shadowBlur=0;ctx.fill();ctx.beginPath();ctx.arc(cx+lookX-iris*.12,cy+lookY-iris*.16,iris*.08,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();const lidWave=Math.sin(progress*Math.PI*4)*ry*.08;ctx.beginPath();ctx.moveTo(cx-rx,cy);ctx.quadraticCurveTo(cx,cy-ry-lidWave,cx+rx,cy);ctx.strokeStyle='rgba(247,247,248,.85)';ctx.lineWidth=3;ctx.stroke();ctx.beginPath();ctx.moveTo(cx-rx,cy);ctx.quadraticCurveTo(cx,cy+ry+lidWave,cx+rx,cy);ctx.stroke();ctx.restore();drawCrawler(cx,cy,rx,ry,time)};
  const drawCrawler=(cx,cy,rx,ry,time)=>{const angle=-Math.PI*.9+progress*Math.PI*5.4+(reduced?0:time*.00018),x=cx+Math.cos(angle)*rx*1.05,y=cy+Math.sin(angle)*ry*1.22;trail.push({x,y});if(trail.length>42)trail.shift();ctx.beginPath();trail.forEach((point,index)=>{if(index===0)ctx.moveTo(point.x,point.y);else ctx.lineTo(point.x,point.y)});ctx.strokeStyle='rgba(198,255,69,.28)';ctx.lineWidth=2;ctx.stroke();ctx.save();ctx.translate(x,y);ctx.rotate(angle+Math.PI/2);ctx.strokeStyle='#c6ff45';ctx.lineWidth=2;for(let side=-1;side<=1;side+=2){for(let leg=0;leg<3;leg++){const ly=(leg-1)*9;ctx.beginPath();ctx.moveTo(side*7,ly);ctx.lineTo(side*(17+Math.sin(time*.004+leg)*3),ly-8+leg*7);ctx.lineTo(side*25,ly+2+leg*4);ctx.stroke()}}ctx.beginPath();ctx.roundRect(-12,-17,24,34,10);ctx.fillStyle='#080809';ctx.fill();ctx.strokeStyle='#c6ff45';ctx.stroke();ctx.fillStyle='#fff';ctx.font='700 17px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('A',0,1);ctx.restore()};
  const drawShards=delta=>{shards=shards.filter(shard=>shard.life>0);shards.forEach(shard=>{shard.vy+=.0009*delta;shard.x+=shard.vx*delta;shard.y+=shard.vy*delta;shard.rotation+=shard.spin*delta;shard.life-=delta;ctx.save();ctx.translate(shard.x,shard.y);ctx.rotate(shard.rotation);ctx.beginPath();ctx.moveTo(-shard.size,shard.size);ctx.lineTo(0,-shard.size);ctx.lineTo(shard.size*.7,shard.size);ctx.closePath();ctx.fillStyle=`rgba(${shard.tint},${Math.max(0,shard.life/900)})`;ctx.fill();ctx.restore()})};
  const frame=time=>{if(!visible)return;const delta=Math.min(32,time-lastTime||16);lastTime=time;ctx.clearRect(0,0,width,height);drawEye(time);drawShards(delta);requestAnimationFrame(frame)};
  const burst=orb=>{const rect=orb.getBoundingClientRect(),host=sticky.getBoundingClientRect(),x=rect.left+rect.width/2-host.left,y=rect.top+rect.height*.35-host.top;for(let i=0;i<22;i++){const angle=Math.PI*2*i/22+Math.random()*.24,speed=.08+Math.random()*.16;shards.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed-.08,rotation:Math.random()*6.2,spin:(Math.random()-.5)*.012,size:4+Math.random()*8,life:700+Math.random()*700,tint:i%3===0?'198,255,69':'210,225,235'})}};
  const updateLightLevel=()=>{const switchedOff=orbs.filter(orb=>orb.classList.contains('is-broken')).length;const allOff=switchedOff===orbs.length;sticky.style.setProperty('--lights-off',String(switchedOff/orbs.length));sticky.classList.toggle('is-lights-out',allOff);if(allOff)document.body.classList.add('home-lights-out')};
  orbs.forEach(orb=>orb.addEventListener('click',()=>{if(orb.classList.contains('is-broken'))return;orb.classList.add('is-broken');orb.setAttribute('aria-pressed','true');updateLightLevel();burst(orb);const memory=memories[orb.dataset.memory];kicker.textContent=memory.kicker;title.textContent=memory.title;copy.textContent=memory.copy;reveal.classList.add('is-open');reveal.setAttribute('aria-hidden','false');close.focus({preventScroll:true})}));
  close.addEventListener('click',()=>{reveal.classList.remove('is-open');reveal.setAttribute('aria-hidden','true')});
  sticky.addEventListener('pointermove',event=>{const rect=sticky.getBoundingClientRect();pointerX=clamp((event.clientX-rect.left)/rect.width,0,1);pointerY=clamp((event.clientY-rect.top)/rect.height,0,1);sticky.classList.toggle('is-eye-hovered',eyeContains(event.clientX,event.clientY))});
  sticky.addEventListener('pointerleave',()=>sticky.classList.remove('is-eye-hovered'));
  sticky.addEventListener('click',event=>{if(event.target.closest('button,a,.memory-reveal')||!eyeContains(event.clientX,event.clientY))return;blinkStartedAt=performance.now();sticky.classList.add('is-eye-blinking');clearTimeout(blinkTimer);blinkTimer=window.setTimeout(()=>sticky.classList.remove('is-eye-blinking'),600)});
  addEventListener('scroll',updateScroll,{passive:true});addEventListener('resize',()=>{resize();updateScroll()});
  new IntersectionObserver(entries=>{const next=entries[0].isIntersecting;if(next&&!visible){visible=true;lastTime=performance.now();requestAnimationFrame(frame)}else visible=next},{rootMargin:'20% 0px'}).observe(sticky);
  orbs.forEach(orb=>orb.setAttribute('aria-pressed','false'));updateLightLevel();resize();updateScroll();
})();
